### ISSUE TITLE
Feature request: custom submit endpoint on mobile

### ISSUE THREAD

**Issue by abdellahaski** [ccwalletio/tracker#124]
Hi,

Would be great if you support the custom submit endpoint on Android.

Been using this feature on PC with my cardano node, would love to be able to do the same on my smartphone on the go.

**Comment by marcuspuchalla** [comment]
Hello @abdellahaski 

Due to problems with CORS policy, adding a custom endpoint on the web or mobile app version was not implemented yet.
We have decided to add this in the future and have already created an internal task for it.

Once it has been implemented and is included in a release, we will let you know and close this task.

Thank you for your request! 

best regards, Marcus

**Comment by marcuspuchalla** [comment]
Hello @abdellahaski

The custom API endpoint can now also be configured on the mobile app.
Please make sure to configure your submit API endpoint and then give it a try. 
If you have any more questions, feel free to comment on this issue.

**Comment by abdellahaski** [comment]
Thanks @marcuspuchalla for the reactivity.
I test it out but I still get the CORS error.
![image](https://user-images.githubusercontent.com/10819089/190191937-efa6410f-763b-4a80-a1d2-8b85a21acc5b.png)

Not sure if the update still didn't reach me or what. I'm on the beta version btw (Android)
