### ISSUE TITLE
Autocomplete/Remember Password Currently Works

### ISSUE THREAD

**Issue by Crypto2099** [ccwalletio/tracker#4]
Currently testing the wallet in Google Chrome (have not tested other browsers) when setting up the wallet and creating a spending password Google Chrome is giving the opportunity to save the password. This seems like a potential security vulnerability that should be disabled (if possible).

![image](https://user-images.githubusercontent.com/63186174/123684742-b1d51c80-d802-11eb-9401-436fb0abdf35.png)

**Comment by MarcelKlammer** [comment]
Not sure about this one. I can see the issue, but it's a user usability feature in the browser. Need to think more about it.

**Comment by pmcl77** [comment]
But as a chrome user you can always say "never" when asked to save passwords, or was this different for you with ccwallet?

**Comment by TrevorBenson** [comment]
Leaving the saved password option in a lite, browser based, crypto wallet that does not require any other authentication or implement any other security to safeguard from theft should not take much effort to review and make a decision. Taking a moment to review:

A bad actor can:
1. Open ccwallet.io
2. Select the mnemonic wallet from the list.
3. Click on send
4. Fill in the address, the amount.
5. Accept the browsers saved spending password.

Now the users wallet is empty and the bad actor did not even need to know the password. 

Given this can happen within 30 seconds of access to someones laptop or desktop what reason would anyone consider this a safe and sane security option?

The bad actor:
1. Does not need any user/password combination to open ccwallet.io
2. Does not require the mnemonic to restore the wallet/account.
2. Does not require the spending password to empty the wallet because it is suggested automatically.

I see no reason that disabling browser form saved passwords should not be implemented as soon as possible. I see this as a VERY big security hole being left wide open. I only hope that this is fixed before the first ADA holder reports having their wallet emptied via ccwallet. There are too many instances where this could happen (malware, faked IT with screenshare, bad actor touching your computer when your back is turned in public). 

I cannot stress any more than I see zero viable reasons this should be considered an acceptable feature to leave enabled.

@Crypto2099 Thanks for pointing this out.

**Comment by Scitz0** [comment]
I hear what you say and they are valid points. Though I still think password management should be up to the client browser to deal with accordingly. But autofill in password fields should hopefully not happen in the upcoming release.
